name: Makefile
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # 2026-1-9
      
      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c # v2.31.1
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-openssl
            make
            
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install build-essential libssl-dev libmariadb-dev

      - if: matrix.os == 'windows-latest'
        run: make -j$(nproc)
        shell: msys2 {0}
      
      - if: matrix.os == 'ubuntu-latest'
        run: make -j$(nproc)
        # assume bash
